### ISSUE TITLE
названия переменных должны быть понятные

### ISSUE THREAD

**Issue by tamazyanarsen** [A1exWolf/ToDoList#1]
https://github.com/A1exWolf/ToDoList/blob/011193079f57619bf6447d7a3411fabd1877d38c/js/main.js#L28

что такое deLi???

везде использей camelCase стиль для наименования переменных, это ко всему проекту относится

**Comment by tamazyanarsen** [comment]
никогда не ищи элементы по названию html-тега

чаще всего используют классы

например, `querySelector('.item')`

**Comment by A1exWolf** [comment]
deLi - это я использую потом для удаления а так поправил название на deleteTagLi .  А `document.querySelectorAll('li')`  Мне выгодно использовать так как я выбираю все list item и удаляю их. Ведь в этом li больше нигде не будет , а так да учту. Ведь когда приложение больше тег li может использоваться в разных местах.
